[package]
name = "rust-codeCoffee"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
dotenvy = "0.15.7"
sea-orm = {version = "1.1.14", features= ["sqlx-postgres","runtime-tokio-rustls",]}
tokio = { version = "1.46.1", features = ["full"] }
